openapi: 3.0.1
info:
  title: dump-server
  description: A restful API for querying osm planet dumps
  version: 1.0.0
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://localhost:8080
paths:
  /dumps:
    get:
      operationId: getDumpsByQuery
      tags:
        - dump
      summary: Get dumps by query
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            default: 10
            minimum: 0
            maximum: 100
          description: The number of dumps to return
        - in: query
          name: from
          schema:
            type: string
            format: date
          description: The date to fetch dumps from
        - in: query
          name: to
          schema:
            type: string
            format: date
          description: The date to fetch dumps until
        - in: query
          name: sort
          description: Date sort order
          schema:
            type: string
            enum: [asc, desc]
            default: desc
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/dump'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
  /dumps/{dumpId}:
    get:
      operationId: getDumpById
      tags:
        - dump
      summary: Get a dump by id
      parameters:
        - in: path
          name: dumpId
          schema:
            type: string
            format: uuid
          required: true
          description: id of the dump to get
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/dump'
        400:
          $ref: '#/components/responses/BadRequest'
        404:
          $ref: '#/components/responses/NotFound'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/error'
  schemas:
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
    dump:
      type: object
      required:
        - id
        - name
        - timestamp
        - path
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        timestamp:
          type: string
          format: date-time
        path:
          type: string
        description:
          type: string
