{{- $releaseName := .Release.Name -}}
{{- $chartName := include "dump-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- if .Values.enableInternalDb }}
  DB_HOST: {{ $releaseName }}-postgresql
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  {{- else }}
  DB_HOST: {{ .Values.dbConfig.host }}
  DB_NAME: {{ .Values.dbConfig.database }}
  {{- end }}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  DB_CERT_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  OBJECT_STORAGE_PROTOCOL: {{ .Values.objectStorageConfig.protocol }}
  OBJECT_STORAGE_HOST: {{ .Values.objectStorageConfig.host }}
  OBJECT_STORAGE_PORT: {{ .Values.objectStorageConfig.port  | quote }}
  OBJECT_STORAGE_PROJECT_ID: {{ .Values.objectStorageConfig.projectId }}
{{- end -}}
