{{- $releaseName := .Release.Name -}}
{{- $chartName := include "dump-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- if .Values.enableInternalDb }}
  DB_HOST: {{ $releaseName }}-postgresql
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase }}
  {{- else }}
  DB_HOST: {{ .Values.dbConfig.host }}
  DB_NAME: {{ .Values.dbConfig.database }}
  {{- end }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  OBJECT_STORAGE_PROTOCOL: {{ .Values.objectStrorageConfig.protocol }}
  OBJECT_STORAGE_HOST: {{ .Values.objectStrorageConfig.host }}
  OBJECT_STORAGE_PORT: {{ .Values.objectStrorageConfig.port  | quote }}
{{- end -}}
