{{- $releaseName := .Release.Name -}}
{{- $chartName := include "dump-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  {{- if .Values.enableInternalDb -}}
  {{- with .Values.postgresql }}
  DB_HOST: {{ $releaseName }}-postgresql
  DB_NAME: {{ .postgresqlDatabase }}
  {{- end -}}
  {{- else -}}
  {{- with .Values.dbConfig }}
  DB_HOST: {{ .host }}
  DB_NAME: {{ .database }}
  {{- end -}}
{{- end -}}
{{- with .Values }}
  LOG_LEVEL: {{ .env.logLevel | quote }}
  OBJECT_STORAGE_PROTOCOL: {{ .objectStrorageConfig.protocol }}
  OBJECT_STORAGE_HOST: {{ .objectStrorageConfig.host }}
  OBJECT_STORAGE_PORT: {{ .objectStrorageConfig.port  | quote }}
{{- end -}}
{{- end }}
