{{- $releaseName := .Release.Name -}}
{{- $chartName := include "dump-server.name" . -}}
{{- $tracingUrl := include "dump-server.tracingUrl" . -}}
{{- $metricsUrl := include "dump-server.metricsUrl" . -}}
{{- $metricsInterval := include "dump-server.metricsInterval" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-configmap
data:
  DB_HOST: {{ .Values.dbConfig.host }}
  DB_NAME: {{ .Values.dbConfig.database }}
  DB_CERT_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.certFileName }}
  DB_CA_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.caFileName }}
  DB_KEY_PATH: /tmp/certs/{{ .Values.dbConfig.sslAuth.keyFileName }}
  OBJECT_STORAGE_PROTOCOL: {{ .Values.objectStorageConfig.protocol }}
  OBJECT_STORAGE_HOST: {{ .Values.objectStorageConfig.host }}
  OBJECT_STORAGE_PORT: {{ .Values.objectStorageConfig.port  | quote }}
  OBJECT_STORAGE_PROJECT_ID: {{ .Values.objectStorageConfig.projectId }}
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  REQUEST_PAYLOAD_LIMIT: {{ .Values.env.requestPayloadLimit | quote }}
  RESPONSE_COMPRESSION_ENABLED: {{ .Values.env.responseCompressionEnabled | quote }}
  {{- if .Values.dbConfig.sslAuth.enabled }}
  DB_ENABLE_SSL_AUTH: "true"
  {{- else }}
  DB_ENABLE_SSL_AUTH: "false"
  {{- end }}
  {{ if .Values.global.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  TELEMETRY_TRACING_RATIO: {{ .Values.env.tracing.ratio | quote }}
  {{ end }}
  {{ if .Values.global.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  TELEMETRY_METRICS_INTERVAL: {{ $metricsInterval }}
  {{ end }}
{{- end -}}
