{{- $releaseName := .Release.Name -}}
{{- $chartName := include "dump-server.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}-secret
    environment: {{ include "dump-server.environment" . }}
    release: {{ $releaseName }}
    {{- include "dump-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.enableInternalDb -}}
  {{- with .Values.postgresql }}
  DB_USERNAME: {{ .postgresqlUsername | default "postgres" | b64enc }}
  DB_PASSWORD: {{ .postgresqlPassword | b64enc }}
  {{- end -}}
  {{- else -}}
  {{- with .Values.dbConfig }}
  DB_USERNAME: {{ .username | b64enc }}
  DB_PASSWORD: {{ .password | b64enc }}
  {{- end -}}
  {{- end -}}
{{- end }}
