global:
  cloudProvider: {}

environment: development
cloudProvider:
  name: azure
  dockerRegistryUrl: 'some_url'

enabled: true
enableInternalDb: false
image:
  repository: 'dump-server'
  tag: 'v1'
replicaCount: 1
env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
# external
dbConfig:
  host: postgresHost
  username: postgres
  password: password
  database: database
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: name.crt
    keyFileName: name.key
    caFileName: name.crt
objectStorageConfig:
  host: s3Host
  port: 9000
  protocol: http
  projectId: 373e47ef2a58d
initialDelaySeconds: 600
resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
route:
  enabled: true
  enableTls: true
  path: /

#internal
postgresql:
  postgresqlUsername: internal_postgres
  postgresqlPassword: internal_password
  postgresqlDatabase: internal_database
