global:
  cloudProvider: {}
  environment: {}
  metrics: {}
  tracing: {}

environment: development
replicaCount: 1
enabled: true
initialDelaySeconds: 600

annotations: {}
podAnnotations: {}

cloudProvider:
  name: openshift
  dockerRegistryUrl: 'my-registry.io'

image:
  repository: 'dump-server'
  tag: 'latest'

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  requestPayloadLimit: 1mb
  responseCompressionEnabled: true
  tracing:
    enabled: false
    url: 'http://localhost:55681/v1/trace'
    ratio: 1
  metrics:
    enabled: false
    interval: 15000
    url: 'http://localhost:55681/v1/metrics'

dbConfig:
  host: postgresHost
  username: postgres
  password: password
  database: database
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: name.crt
    keyFileName: name.key
    caFileName: name.crt

objectStorageConfig:
  host: s3Host
  port: 9000
  protocol: http
  projectId: 373e47ef2a58d

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

route:
  enabled: true
  enableTls: true
  path: /
